services:
  db:
    image: postgres:v1
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: manchester
    network_mode: host
  app:
    depends_on:
      - db
    image: my_app_img:v1
    restart: always
    network_mode: host
